dist: trusty
cache:
  directories:
    - $HOME/.stack
before_install:
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 575159689BEFB442
- echo 'deb http://download.fpcomplete.com/ubuntu precise main'|sudo tee /etc/apt/sources.list.d/fpco.list
- sudo apt-get update -qq
- sudo apt-get install stack liblapack-dev libblas-dev -y -qq

# Install Z3 from their GitHub release
# Inspired from Levent Erkok's SBV TravisCI file
- export Z3=z3-4.6.0-x86-ubuntu-14.04.zip
- echo "Linux Z3 $Z3"
- export Z3Base=`basename $Z3 .zip`
- wget --quiet -L -O z3.zip http://github.com/Z3Prover/bin/raw/master/releases/$Z3
- unzip -q z3.zip -d z3_downloaded
- /bin/rm z3.zip
- export PATH=$PATH:$PWD/z3_downloaded/$Z3Base/bin
- z3 --version

- cd ..
- git clone https://github.com/camfort/fortran-src
- cd fortran-src
- echo $TRAVIS_TAG
- "ruby -e \"ENV['TRAVIS_TAG'] =~ /v/ && system('git checkout $(git tag | tail -n1)')\""
- cd $TRAVIS_BUILD_DIR
- stack setup
script:
- "GHC_OPTIONS=\"--ghc-options=\"$(ruby -e 'print (ENV[%q|TRAVIS_TAG|] =~ /v/ ? %q|-O3| : %q|-O0|)')\"\""
- echo $GHC_OPTIONS
- $(ruby -e "ENV['GHC_OPTIONS'] =~ /O3/ && puts('travis_wait 60')") stack haddock --test $GHC_OPTIONS
after_success:
- cp "$(stack exec -- which camfort)" camfort
- tar -cvzf camfort-x64-Linux.tar.gz camfort
- sha256sum camfort-x64-Linux.tar.gz
deploy:
- provider: releases
  api_key:
    secure: "Y/2Lbhm5E+iTY7l9Jmz0xaDwza7GiFIzakfrdim1s4jqIRqlkrlnHGU13U2g2j6i5Klx7TGrmivY8p17tXwQE9ubD5Gc1TgTMj+AaPIeKmDAA0fZ8YOxEQQEso/LTBdCPuP7pgro5vdUYi6Nuj7MDte8itAzFEzBrXn6WYwJN1nIaQR9TDc1ktCDjnxvp6zD3XrgCDlPgvopYJb+6ozD6VOKmBvNUKp2SjkCstSDn0j5/olyjzUFIpTcrtT9pGct5F9QIYuC9UnLZ1MNPMXjJZR27g+MrWI8MhAgLwqbrYewaLI6Jk2dyC7SDt30oK8+vGZ6pDN3QYmmbQvL40Etfq+ItY02Fz8DKO68qVYGxreuulM91AHSNlpWPsEv5A/oBtih/jJ1yOTe5UusC6dk2Ji95IkMeRZteaRj2NOSxWErElZZUcoQ31EWRvOzPgmmRcp7+Xmmc3QKLWQCqCqXcrGJRq++sROo12ZNzNu1TIPns/YG1D75pHjMx+y0AayoIeUF8pJND3CdZEGDchB35IRyCzzEKBkswLod1BXZKO42jWThN3t53ZkuILLVOwTxmefQK9jLXUjRTrAvCcLPFEL1aJQK1Ijf09hxDUme5IjgZZ1l09ITNbI5giCuEWyqmZLmECUoVWskBFMJ7ZZlZ7nRQQ/hVKb/Nlyj4PIhOBI="
  file: camfort-x64-Linux.tar.gz
  skip_cleanup: true
  on:
    repo: camfort/camfort
    tags: true
- provider: hackage
  username: madgen
  file:
  password:
    secure: "e5hKqdGtJLtF0+6cBEUkabUTbEGeEMdikS2qhe2SAkmYS9+gmZmCr/cdrTLrEzaF7qljvIv8gWXXjQCiMqVX+OUc+3RsPvxug5le5Zx0Qhk1A25U6p7OmzjhSP84ISnJhwUvB/is2jWbDanTQw5jaDTD1V+5NufjVYKgrZS3MUpMuad9MVaxxB4fHFNQcAwpe0t5mCwoW8dA1QeMBH1nGSxvThYcMeLhohuz5DkUcr7NVFccmAbtybmh9voPNeZecM2nNJTOHQnORCk1EUMedQn762RHOVuLL/hndkIbDjhsChp8t83W7rpoEChCafLUxpbEtTruFLMjS2lARl7o1V0M+oCnuU8ZZMhB5BSGvg6rX4Ft8wgrwSKnHohAOPtxJICf360w4lmfpyjQbzcnLFdZ8KhoXR3Qi03xvy2ltuzTyNxSJW5K41Dnqq7PyLkvWGY6WFsfcFKmibW2TjOtUmmDPOXqe6oZaKK4Il5A9adkpmghBndUahQBBqvwmysnT3Rr8fxmg6zF7JDwkrLzbTGhD3VMAUcFrtxe3K49wtmCZLoGSoAZTorzuMFDp3uFYLIANxeV6EpaIlwg+BFnIi5+LOKEF1H02fd57wiroVxzx8hH9KcJZWADYX3LjR8LEztwvERThFiMA2Mr/Su1uGL6rndoENys55s6wr877OA="
  on:
    repo: camfort/camfort
    tags: true
