flags: {}
extra-package-dbs: []
packages:
- '.'
- location: ../fortran-src
  extra-dep: true
- location:
    git: https://github.com/camfort/verifiable-expressions.git
    commit: 1b76530f07aa85613b89b01b6ae638d33b93c899
  extra-dep: true
extra-deps:
- syz-0.2.0.0
- vinyl-0.8.1.1
resolver: lts-11.9
allow-newer: true
